#!/usr/bin/env python3
"""
context-pack.py — Pre-compaction flush.
Reads SOUL.md, HEARTBEAT.md, all memory/{date}.md files,
and writes a curated MEMORY.md with deduplicated facts.
Run before context window fills: python context-pack.py
"""
import re
from pathlib import Path
from datetime import datetime

BASE = Path(__file__).parent.parent
SOUL = BASE / "core" / "SOUL.md"
HEARTBEAT = BASE / "core" / "HEARTBEAT.md"
MEMORY_DIR = BASE / "memory"
MEMORY_OUT = BASE / "MEMORY.md"
MAX_LINES = 190  # stay under 200-line truncation


def extract_heartbeat_log(text: str) -> list[str]:
    """Return the last N log entries from HEARTBEAT.md."""
    in_log = False
    entries: list[str] = []
    current: list[str] = []
    for line in text.splitlines():
        if line.strip() == "## Log":
            in_log = True
            continue
        if in_log and line.startswith("## "):
            break
        if in_log:
            if line.startswith("### "):
                if current:
                    entries.append("\n".join(current))
                current = [line]
            elif current:
                current.append(line)
    if current:
        entries.append("\n".join(current))
    return entries[-5:]  # keep last 5 entries


def collect_daily_facts(memory_dir: Path) -> list[str]:
    """Collect 'Learned' and 'Key Decisions' bullets from all daily logs."""
    facts: list[str] = []
    seen: set[str] = set()
    for md_file in sorted(memory_dir.glob("????-??-??.md")):
        text = md_file.read_text(encoding="utf-8")
        in_section = False
        for line in text.splitlines():
            if line.startswith("## Key Decisions") or line.startswith("## Learned"):
                in_section = True
                continue
            if in_section and line.startswith("## "):
                in_section = False
            if in_section and line.startswith("- "):
                stripped = line.strip()
                if stripped not in seen:
                    seen.add(stripped)
                    facts.append(f"{stripped}  *(from {md_file.stem})*")
    return facts


def build_memory(soul: str, hb_entries: list[str], facts: list[str]) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = [
        f"# MEMORY.md — auto-generated by context-pack.py",
        f"*Last updated: {now}*",
        "",
        "## Identity",
    ]
    # Pull first non-blank, non-header lines from SOUL.md
    for line in soul.splitlines():
        if line.startswith("#") or not line.strip():
            continue
        lines.append(f"- {line.strip()}")
        if len(lines) > 15:
            break

    lines += ["", "## Durable Facts / Key Decisions"]
    for f in facts:
        lines.append(f)
        if len(lines) >= MAX_LINES - 20:
            lines.append("- *(truncated — run context-pack.py again for full output)*")
            break

    lines += ["", "## Recent Heartbeat Log (last 5 sessions)"]
    for entry in hb_entries:
        lines.append(entry)
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    soul_text = SOUL.read_text(encoding="utf-8") if SOUL.exists() else ""
    hb_text = HEARTBEAT.read_text(encoding="utf-8") if HEARTBEAT.exists() else ""
    hb_entries = extract_heartbeat_log(hb_text)
    facts = collect_daily_facts(MEMORY_DIR) if MEMORY_DIR.exists() else []
    content = build_memory(soul_text, hb_entries, facts)

    MEMORY_OUT.write_text(content, encoding="utf-8")
    line_count = len(content.splitlines())
    print(f"[context-pack] Wrote MEMORY.md — {line_count} lines")
    if line_count > MAX_LINES:
        print(f"[context-pack] WARNING: {line_count} lines exceeds {MAX_LINES} truncation threshold")


if __name__ == "__main__":
    main()
