#!/usr/bin/env python3
"""
idea-collider.py — picks two random concepts, generates a 200-word product pitch via Claude API,
appends to IDEAS.md. Runs standalone or on a schedule.
"""

import os
import random
import sys
from datetime import date
from pathlib import Path

BASE = Path(__file__).parent.parent
IDEAS_FILE = BASE / "IDEAS.md"

# Seed concept list — grows over time as IDEAS.md is written
CONCEPTS = [
    "recurring subscription", "offline-first app", "voice interface", "habit tracker",
    "anonymous feedback", "AI sommelier", "dead man's switch", "ephemeral social network",
    "reverse mentorship", "location-aware reminders", "public commitment contract",
    "digital will", "ambient noise generator", "focus sprints", "memory palace",
    "gratitude journal", "shadow calendar", "micro-SaaS", "API gateway", "semantic search",
    "chaos engineering", "trust score", "skill decay tracker", "context switching cost",
    "sleep debt tracker", "decision journal", "energy budget", "social proof engine",
    "accountability partner", "mood-based playlist", "friction as a feature",
    "opt-out defaults", "dark UX detector", "nudge engine", "behavioral contract",
    "time capsule app", "async standup", "meeting tax calculator", "boredom scheduler",
    "serendipity engine", "knowledge decay", "digital detox tracker",
]


def pick_pair() -> tuple[str, str]:
    a, b = random.sample(CONCEPTS, 2)
    return a, b


def generate_pitch(concept_a: str, concept_b: str) -> str:
    try:
        import anthropic
    except ImportError:
        return f"[anthropic SDK not installed — install with: pip install anthropic]\nConcepts: {concept_a} + {concept_b}"

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return f"[ANTHROPIC_API_KEY not set]\nConcepts: {concept_a} + {concept_b}"

    client = anthropic.Anthropic(api_key=api_key)
    prompt = (
        f"You are a product ideation engine. Combine these two concepts into a compelling "
        f"200-word product pitch for a SaaS or app:\n\n"
        f"Concept A: {concept_a}\n"
        f"Concept B: {concept_b}\n\n"
        f"Write the pitch directly. No preamble. No headers. Just the pitch."
    )
    msg = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=400,
        messages=[{"role": "user", "content": prompt}],
    )
    return msg.content[0].text.strip()


def append_idea(concept_a: str, concept_b: str, pitch: str) -> None:
    today = date.today().isoformat()
    entry = f"\n## {today} — {concept_a} × {concept_b}\n\n{pitch}\n"
    if not IDEAS_FILE.exists():
        IDEAS_FILE.write_text("# IDEAS\n\nGenerated by idea-collider.py.\n", encoding="utf-8")
    with IDEAS_FILE.open("a", encoding="utf-8") as f:
        f.write(entry)
    print(f"Appended to {IDEAS_FILE}")


def main() -> None:
    a, b = pick_pair()
    print(f"Colliding: {a!r} × {b!r} ...")
    pitch = generate_pitch(a, b)
    print(f"\n{pitch}\n")
    append_idea(a, b, pitch)


if __name__ == "__main__":
    main()
